name: 🚀 Deploy server on push

on:
  push:
    branches: [ main ]
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: e142334-ftp.services.easyname.eu
        username: 224504ftp1
        password: ${{ secrets.STAGING_FTP_PASSWORD }}
        server-dir: ./ssa-server/
        local-dir: ./server/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.idea/**
          
