name: ✨Eslint Find & Fix
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: NPM Init
      run: npm init --force --yes
    - name: Install modules
      run: npm i --save-dev eslint
    - name: Config ESLint
      run: npm install @eslint/config -- --config semistandard
    - name: Run ESLint
      run: eslint eslint --fix **.js
