name: ✨ Eslint Find & Fix
on: 
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: NPM Init
      run: npm init --force --yes
    - name: Install modules
      run: npm i --save-dev eslint
    - name: Config ESLint
      run: npm init @eslint/config -- --config semistandard
    - name: Run ESLint
      run: npx eslint --fix **.js --no-error-on-unmatched-pattern
