name: 🚀 Deploy website on push

on:
  push:
    branches: [ main ]
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        ftp-server: e142334-ftp.services.easyname.eu
        ftp-username: 224504ftp1
        ftp-password: ${{ secrets.STAGING_FTP_PASSWORD }}
        local-dir: ./html/ssa-server/
